# Dockerfile
FROM node:lts-alpine

# Instalar dependencias de sistema si son necesarias
RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --production

COPY . .

# Elastic Beanstalk espera este puerto
ENV PORT=8080
EXPOSE 8080

CMD ["npm", "run", "start"]
