# Etapa 1: construir la app
FROM node:lts-alpine as builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install

COPY . ./
RUN npm run build

# Etapa 2: servir la app con nginx
FROM nginx:alpine

# Copia el archivo de configuración de NGINX (opcional)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia los archivos compilados
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
