name: Deploy Frontend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t rodolforamirez/docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true rodolforamirez/docker-react npm run test

      - name: Create deployment package (ZIP)
        run: zip -r deployment.zip . -x '*.git*' 'node_modules/*' 'tests/*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-env-1
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deployment.zip
