name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
permissions:
  id-token: write
  pages: write 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t rodolforamirez/docker-react -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true rodolforamirez/docker-react npm run test
      - name: Generate deployment package
        run: zip -r deployment.zip . -x '*.git*'
      - name: Deploy to EB
        if: success()
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend 
          environment_name: Frontend-env-1
          version_label: ${{ github.sha }}
          region: us-east-1
          existing_bucket_name: elasticbeanstalk-us-east-1-469548819526
          deployment_package: deployment.zip
            